"""empty message

Revision ID: c0205bc18ef6
Revises: 09790819a68a
Create Date: 2020-11-07 14:50:49.438321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0205bc18ef6'
down_revision = '09790819a68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('beginning', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'beginning')
    # ### end Alembic commands ###
