"""empty message

Revision ID: ed5286d3bc69
Revises: b69f2c9b351d
Create Date: 2020-11-10 15:49:06.849199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5286d3bc69'
down_revision = 'b69f2c9b351d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('beginning', sa.String(length=280), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_published', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drafts', sa.Column('published_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drafts', 'works', ['published_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drafts', type_='foreignkey')
    op.drop_column('drafts', 'published_id')
    op.drop_table('works')
    # ### end Alembic commands ###
