"""empty message

Revision ID: 998fe4022031
Revises: b1d01aaa0102
Create Date: 2020-11-15 14:41:06.283900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998fe4022031'
down_revision = 'b1d01aaa0102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saves',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'work_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saves')
    # ### end Alembic commands ###
